FROM eclipse-temurin:17.0.5_8-jre

COPY ./connectFour.jar /home/connectfour/connectFour.jar
WORKDIR /home/connectfour

LABEL org.opencontainers.image.source=https://github.com/Day-Hawk/connect-four
LABEL org.opencontainers.image.description="Connect Four for Docker"
LABEL org.opencontainers.image.licenses="Apache License 2.0"


RUN chmod -Rv 7777 /home/connectfour/connectFour.jar

CMD ["java", "-jar", "connectFour.jar"]